### ISSUE TITLE
Replace else with explicit if statement in R functions

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/cloudos#7]
@sk-sahu thanks for being on the Jenny Bryan side of life 😄 !

We can update R functions replacing `else` with the explicit if function in the following places:

- [ ] [create_cohort.R#L40-L41](https://github.com/lifebit-ai/cloudos/blob/c7d081e2708f30af4eb91703d920abe3bc1c794f/R/create_cohort.R#L40-L41)
- [ ] [extract_genotypic_data.R#L40-L42](https://github.com/lifebit-ai/cloudos/blob/c7d081e2708f30af4eb91703d920abe3bc1c794f/R/extract_genotypic_data.R#L40-L42)
- [ ] [extract_participants.R#L31-L34](https://github.com/lifebit-ai/cloudos/blob/c7d081e2708f30af4eb91703d920abe3bc1c794f/R/extract_participants.R#L31-L34)
- [ ] [list_cohorts.R#L35-L38](https://github.com/lifebit-ai/cloudos/blob/c7d081e2708f30af4eb91703d920abe3bc1c794f/R/list_cohorts.R#L35-L38)

So in principle as an example the following snippet, when `if`-ified would lokk like this:

https://github.com/lifebit-ai/cloudos/blob/1e1ec0098ff91108a6c1c8afacdf5a0f1d35a492/R/create_cohort.R#L37-L46

```r
if (!r$status_code == 200) { 
    stop("Something went wrong. Not able to create a cohort") 
 }
if (r$status_code == 200){
    message("Cohort named ", cohort_name, " created successfully. Bellow are the details") 
    res <- httr::content(r) 
    # into a dataframe 
    res_df <- do.call(rbind, res) 
    colnames(res_df) <- "details" 
    return(res_df) 
 } 
```

_Originally posted by @cgpu in https://github.com/lifebit-ai/cloudos/pull/5#discussion_r473594262_

**Comment by sk-sahu** [comment]
Most of them are replaced with only `if`
